import type { RepoHealthCheck } from "../repo-health/types";
import type { QueueItem } from "../approval-queue/queue";

export type MaintainerReportInput = {
  repoFullName: string;
  generatedAt: Date;
  mode: "demo" | "live";
  checks: RepoHealthCheck[];
  pendingItems: QueueItem[];
  recentAudit: Array<{ action: string; createdAt: string }>;
  knownLimitations: string[];
};

const STATUS_ICON: Record<RepoHealthCheck["status"], string> = {
  present: "✓",
  partial: "~",
  missing: "✗",
  not_verified: "?",
};

const SOURCE_LABEL: Record<QueueItem["source"], string> = {
  issue_triage: "Issue triage",
  pr_summary: "PR summary",
  release_draft: "Release draft",
  documentation: "Documentation",
};

function escape(value: string): string {
  // Strip control chars that would corrupt Markdown (preserve tab \t and newline \n).
  // eslint-disable-next-line no-control-regex
  return value.replace(/[\u0000-\u0008\u000b-\u001f\u007f]/g, " ");
}

export function generateMaintainerReport(input: MaintainerReportInput): string {
  const lines: string[] = [];
  const heading = input.mode === "demo" ? "demo data" : "live data";
  lines.push(`# Maintainer report — ${escape(input.repoFullName)}`);
  lines.push("");
  lines.push(`*Generated ${input.generatedAt.toISOString()} from ${heading}.*`);
  lines.push("");
  lines.push(
    "> Advisory report. MaintainerOS heuristics are not a substitute for a formal audit, security review, or production sign-off. Do not treat this document as evidence of certification.",
  );
  lines.push("");

  lines.push("## Repository readiness");
  lines.push("");
  if (input.checks.length === 0) {
    lines.push("_No checks available._");
  } else {
    lines.push("| Check | Status | Confidence | Evidence |");
    lines.push("|---|---|---|---|");
    for (const c of input.checks) {
      lines.push(
        `| ${escape(c.name)} | ${STATUS_ICON[c.status]} ${c.status} | ${c.confidence} | ${escape(c.evidence)} |`,
      );
    }
  }
  lines.push("");

  lines.push("## Pending AI drafts");
  lines.push("");
  if (input.pendingItems.length === 0) {
    lines.push("_No pending drafts._");
  } else {
    for (const i of input.pendingItems) {
      lines.push(`- **${SOURCE_LABEL[i.source]}** · ${i.approvalStatus} — ${escape(i.title)}`);
    }
  }
  lines.push("");

  lines.push("## Recent audit activity");
  lines.push("");
  if (input.recentAudit.length === 0) {
    lines.push("_No recent audit entries._");
  } else {
    for (const a of input.recentAudit.slice(0, 25)) {
      lines.push(`- \`${escape(a.action)}\` at ${a.createdAt}`);
    }
  }
  lines.push("");

  lines.push("## Recommended next actions");
  lines.push("");
  const actions = input.checks
    .filter((c) => c.status !== "present" && c.nextAction)
    .slice(0, 10)
    .map((c) => `- ${escape(c.name)}: ${escape(c.nextAction!)}`);
  if (actions.length === 0) {
    lines.push("_All advisory checks already in a good state._");
  } else {
    lines.push(...actions);
  }
  lines.push("");

  lines.push("## Known limitations");
  lines.push("");
  for (const l of input.knownLimitations) {
    lines.push(`- ${escape(l)}`);
  }
  if (input.knownLimitations.length === 0) {
    lines.push("- None listed.");
  }
  lines.push("");

  lines.push("---");
  lines.push("");
  lines.push(
    "Generated by MaintainerOS. No secrets, tokens, session data, or raw request logs are included in this report.",
  );

  return lines.join("\n");
}
